on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  auto_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      # check if have a diff
      - name: Run format code with uv
        run: |
          uv tool run ruff format .

      # check diff
      - name: Check diff
        id: is_diff
        continue-on-error: true
        run: |
          # show diff
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No changes to the output"
            # set output variable
            echo "is_diff=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "is_diff=true" >> $GITHUB_ENV
          fi

      # commit changes
      - name: Commit changes
        if: env.is_diff == 'true'
        run: |
          git config --local user.email "auto_format@kgym.com"
          git config --local user.name "auto_format"
          git add .
          git commit -m "Auto format code on $(date)"
          git push
